github.com:
    users:
        MailerDaemon4:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: MailerDaemon4
